/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Dean;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import java.awt.CardLayout;
import javax.swing.JPanel;
import Business.Newbie.NewbieDetailsDirectory;
import Business.Organization.AmbassadorOrganization;
import Business.Organization.NewbieOrganization;
import Business.Organization.DeanOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;

/**
 *
 * @author chels
 */
public class DeanWorkAreaJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private NewbieDetailsDirectory newbieDetailsDirectory;
    private EcoSystem business;
    private UserAccount account;
    
    private DeanOrganization deanorganization;
    
    private Organization org;
    private Enterprise enterprise;
    private Network network;

    /**
     * Creates new form DeanWorkAreaJPanel
     */
    public DeanWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise, Network network) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.newbieDetailsDirectory=newbieDetailsDirectory;
        this.network =network;
        this.account=account;
        this.deanorganization=(DeanOrganization)organization;
        this.enterprise=enterprise;
        this.org=organization;
        System.out.println(network);
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ambassadorBtn = new javax.swing.JButton();
        advisorBtn = new javax.swing.JButton();
        requestTestJButton = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Dean Work Area");

        ambassadorBtn.setText("Manage Ambassador's Requests");
        ambassadorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ambassadorBtnActionPerformed(evt);
            }
        });

        advisorBtn.setText("Manage Advisor's Requests");
        advisorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                advisorBtnActionPerformed(evt);
            }
        });

        requestTestJButton.setText("Request to University Dean");
        requestTestJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestTestJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(ambassadorBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addComponent(advisorBtn)
                .addGap(64, 64, 64))
            .addGroup(layout.createSequentialGroup()
                .addGap(187, 187, 187)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(requestTestJButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(106, 106, 106)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ambassadorBtn)
                    .addComponent(advisorBtn))
                .addGap(74, 74, 74)
                .addComponent(requestTestJButton)
                .addContainerGap(108, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ambassadorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ambassadorBtnActionPerformed
        // TODO add your handling code here:

        ManageAmbassadorJPanel majp= new ManageAmbassadorJPanel(userProcessContainer, account, deanorganization, enterprise);
         userProcessContainer.add("ManageAmbassadorJPanel", majp);
        CardLayout layout= (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_ambassadorBtnActionPerformed

    private void advisorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_advisorBtnActionPerformed
        // TODO add your handling code here:
        ManageAdvisorJPanel madj = new ManageAdvisorJPanel(userProcessContainer, account, deanorganization, enterprise);
        userProcessContainer.add("ManageAdvisorJPanel", madj);
        CardLayout layout= (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_advisorBtnActionPerformed

    private void requestTestJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestTestJButtonActionPerformed

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("DeanRequestJPanel", new DeanRequestJPanel(userProcessContainer, account, org, enterprise, business, network));
        layout.next(userProcessContainer);
    }//GEN-LAST:event_requestTestJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton advisorBtn;
    private javax.swing.JButton ambassadorBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton requestTestJButton;
    // End of variables declaration//GEN-END:variables
}
