/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Dean;

import Business.Organization.DeanOrganization;
import Business.UserAccount.UserAccount;
import javax.swing.JPanel;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.GradStudentOrganization;
import Business.Organization.NewbieOrganization;
import Business.Organization.Organization;
import Business.Organization.AdvisorOrganization;
import Business.WorkQueue.LabTestWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author chels
 */
public class ManageAdvisorJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private DeanOrganization deanorganization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    //private AdvisorOrganization advisorOrganization;

    /**
     * Creates new form ManageAdvisorJPanel
     */
    public ManageAdvisorJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise) {
        initComponents();
         this.userProcessContainer = userProcessContainer;
        this.deanorganization = (DeanOrganization)organization;
        this.enterprise = enterprise;
        this.userAccount=account;
        populateAdvisorReqTbl();
     
    }
    public void populateAdvisorReqTbl(){
        Organization org=null;
         for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
            if (organization instanceof AdvisorOrganization){
            org = organization;
        DefaultTableModel model = (DefaultTableModel) advisroreqTbl.getModel();
        model.setRowCount(0);
        for(WorkRequest request : org.getWorkQueue().getWorkRequestList()){
            Object[] row = new Object[2];
            row[0] = request;
            row[1]=request.getSender();
            model.addRow(row);
        }
            }
        
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of t
     * his method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AnalyzeBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ambassadorreqTbl = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        advisroreqTbl = new javax.swing.JTable();

        AnalyzeBtn.setText("Analyze Requests");

        ambassadorreqTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Message", "Sender"
            }
        ));
        jScrollPane1.setViewportView(ambassadorreqTbl);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Manage Advisor Work Request");

        advisroreqTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Message", "Sender"
            }
        ));
        jScrollPane2.setViewportView(advisroreqTbl);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(120, 120, 120))
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(214, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AnalyzeBtn;
    private javax.swing.JTable advisroreqTbl;
    private javax.swing.JTable ambassadorreqTbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
