/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.GradStudent;
import Business.Employee.Employee;
import Business.Organization.GradStudentOrganization;
import Business.Enterprise.Enterprise;
import javax.swing.JPanel;
import Business.GradStudent.GradStudent;
import Business.GradStudent.GradStudentDirectory;
import Business.Organization.AmbassadorOrganization;
import Business.Organization.Organization;
//mport static Business.Organization.Organization.Type.Newbie;
import userinterface.AmbassadorRole.AmbassadorReqWorkAreaJPanel;

import java.awt.CardLayout;
import java.awt.Component;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author chels
 */
public class GradStudentFirstTimerJPanel extends javax.swing.JPanel {
    private JPanel userprocesscontainer;
    private GradStudentDirectory gradStudentDirectory;
    private Enterprise enterprise;
    private Organization org;
    

    /**
     * Creates new form GradStudentFirstTimerJPanel
     */
    

    GradStudentFirstTimerJPanel(JPanel userProcessContainer, Enterprise enterprise, Organization oorganization) {
         initComponents();
        this.userprocesscontainer = userprocesscontainer;
        this.org=oorganization;
        //this.newbieDetailsDirectory = enterprise.getNds;
        this.enterprise=enterprise;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        GradStudentSignUpBtn = new javax.swing.JButton();
        TFFname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TFmailid = new javax.swing.JTextField();
        courseCB = new javax.swing.JComboBox<>();
        CBethini = new javax.swing.JComboBox<>();
        backBtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        TFLname1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        courseTaken1Txt = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        courseTaken2Txt = new javax.swing.JTextField();
        currentsemCB = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        PlaceTF = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();

        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Grad Student First Timer");
        add(jLabel1);
        jLabel1.setBounds(234, 11, 220, 22);

        jLabel8.setText("Course:");
        add(jLabel8);
        jLabel8.setBounds(180, 183, 38, 14);

        jLabel9.setText("FirstName:");
        add(jLabel9);
        jLabel9.setBounds(179, 117, 52, 14);

        GradStudentSignUpBtn.setText("Submit");
        GradStudentSignUpBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GradStudentSignUpBtnActionPerformed(evt);
            }
        });
        add(GradStudentSignUpBtn);
        GradStudentSignUpBtn.setBounds(303, 475, 67, 23);
        add(TFFname);
        TFFname.setBounds(301, 114, 72, 20);

        jLabel3.setText("LastName:");
        add(jLabel3);
        jLabel3.setBounds(180, 153, 51, 14);

        jLabel4.setText("Ethinicity:");
        add(jLabel4);
        jLabel4.setBounds(180, 332, 47, 14);

        jLabel5.setText("Email-ID");
        add(jLabel5);
        jLabel5.setBounds(180, 371, 39, 14);

        TFmailid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFmailidActionPerformed(evt);
            }
        });
        add(TFmailid);
        TFmailid.setBounds(303, 368, 80, 20);

        courseCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MSIS", "MSEM", "MSTSM" }));
        add(courseCB);
        courseCB.setBounds(303, 183, 80, 22);

        CBethini.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Indian", "Chinese", "American" }));
        add(CBethini);
        CBethini.setBounds(303, 329, 80, 22);

        backBtn.setText("Back");
        add(backBtn);
        backBtn.setBounds(90, 475, 57, 23);

        jLabel6.setText("Current Sem:");
        add(jLabel6);
        jLabel6.setBounds(180, 221, 64, 14);

        TFLname1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFLname1ActionPerformed(evt);
            }
        });
        add(TFLname1);
        TFLname1.setBounds(303, 150, 70, 20);

        jLabel7.setText("Courses Taken 1:");
        add(jLabel7);
        jLabel7.setBounds(180, 256, 84, 14);

        courseTaken1Txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseTaken1TxtActionPerformed(evt);
            }
        });
        add(courseTaken1Txt);
        courseTaken1Txt.setBounds(303, 253, 70, 20);

        jLabel10.setText("Courses Taken 2:");
        add(jLabel10);
        jLabel10.setBounds(180, 294, 84, 14);

        courseTaken2Txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseTaken2TxtActionPerformed(evt);
            }
        });
        add(courseTaken2Txt);
        courseTaken2Txt.setBounds(303, 291, 70, 20);

        currentsemCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));
        add(currentsemCB);
        currentsemCB.setBounds(300, 220, 80, 22);

        jLabel2.setText("Place");
        add(jLabel2);
        jLabel2.setBounds(180, 420, 50, 14);
        add(PlaceTF);
        PlaceTF.setBounds(300, 410, 80, 20);
        add(jPanel1);
        jPanel1.setBounds(790, 0, 100, 100);

        jPanel2.setLayout(null);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/GradStudent/who are you.jpg"))); // NOI18N
        jPanel2.add(jLabel11);
        jLabel11.setBounds(70, 30, 250, 380);

        add(jPanel2);
        jPanel2.setBounds(580, 70, 370, 450);
    }// </editor-fold>//GEN-END:initComponents

    private void GradStudentSignUpBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GradStudentSignUpBtnActionPerformed
        // TODO add your handling code here:
        //NewbieDetailsDirectory nds = enterprise.getNds();
        String name = TFFname.getText();
        String lastn = TFLname1.getText();
        String cour = (String)courseCB.getSelectedItem();
        String current1= courseTaken1Txt.getText();
        String current2=courseTaken2Txt.getText();
        String place = PlaceTF.getText();
        //String course = TFcourse.getText();
        //String currentSem=currentSemTxt.getText();
        String currentsem =(String)currentsemCB.getSelectedItem();
        String ethini = (String)CBethini.getSelectedItem();
        String Email = TFmailid.getText();
          if(TFFname.getText().isEmpty() || TFLname1.getText().isEmpty() || TFmailid.getText().isEmpty()|| courseTaken1Txt.getText().isEmpty() || courseTaken2Txt.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null,"Please fill all the fields");
            
            
        }
        
        else if(!name.matches("[a-z,A-Z,]+") || !lastn.matches("[a-z,A-Z,]+"))
        {
           JOptionPane.showMessageDialog(null,"Please enter characters for names fields"); 
        }
        
       
       else
        {
            
        if(!(Pattern.matches("^[a-zA-Z0-9]+[@]{1}[a-zA-Z0-9]+[.]{1}+[a-zA-Z0-9]+$", TFmailid.getText()))){
            JOptionPane.showMessageDialog(null,"Please enter a valid e-mail");
        }
        else {
            GradStudent gs=org.getGsd().createGradStudent();
        gs.setFName(name);
        gs.setLName(lastn);
        gs.setCourse(cour);
        gs.setCurrentSem(currentsem);
        gs.setCoursetaken1(current1);
        gs.setCoursetaken2(current2);
        gs.setEthinicity(ethini);
        gs.setEmail(Email);
        gs.setFName(name);
        gs.setPlace(place);
        System.out.println(gs.getFName());
        GradStudentSignUpBtn.setEnabled(false);
        
        JOptionPane.showMessageDialog(null,"Successfully Submitted");
        }
        }
        
        
        
        //System.out.println(enterprise.getGsd());
        //newbieDetailsDirectory.createNewbieDetails(newbie);

       
        
    }//GEN-LAST:event_GradStudentSignUpBtnActionPerformed

    private void TFmailidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFmailidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFmailidActionPerformed

    private void TFLname1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFLname1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFLname1ActionPerformed

    private void courseTaken1TxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseTaken1TxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_courseTaken1TxtActionPerformed

    private void courseTaken2TxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseTaken2TxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_courseTaken2TxtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBethini;
    private javax.swing.JButton GradStudentSignUpBtn;
    private javax.swing.JTextField PlaceTF;
    private javax.swing.JTextField TFFname;
    private javax.swing.JTextField TFLname1;
    private javax.swing.JTextField TFmailid;
    private javax.swing.JButton backBtn;
    private javax.swing.JComboBox<String> courseCB;
    private javax.swing.JTextField courseTaken1Txt;
    private javax.swing.JTextField courseTaken2Txt;
    private javax.swing.JComboBox<String> currentsemCB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
