/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.GradStudent;

import java.awt.CardLayout;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.GradStudent.GradStudent;
import java.awt.CardLayout;
import javax.swing.JPanel;
import Business.Newbie.NewbieDetailsDirectory;
import Business.Organization.AmbassadorOrganization;
import Business.Organization.GradStudentOrganization;
import Business.Organization.AdvisorOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkRequest;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author chels
 */
public class GradStudentWorkAreaJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private EcoSystem business;
    private UserAccount account;
    private GradStudentOrganization oorganization;
    private Organization organization;
   private Organization org;
    private Enterprise enterprise;
    private GradStudent gs;

    /**
     * Creates new form GradStudentWorkAreaJPanel
     */
    public GradStudentWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, GradStudentOrganization organization, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.org=org;
        this.account=account;
        this.oorganization=organization;
        this.enterprise=enterprise;
        
    }
    
    
    
         
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        Continue = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        gradStudentFirstTimerBtn = new javax.swing.JButton();
        Continue1 = new javax.swing.JButton();
        chatBtn = new javax.swing.JButton();

        jButton1.setText("FirstTimer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Continue.setText("Continue");
        Continue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContinueActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Grad Student Work Area");

        gradStudentFirstTimerBtn.setText("FirstTimer");
        gradStudentFirstTimerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gradStudentFirstTimerBtnActionPerformed(evt);
            }
        });

        Continue1.setText("Continue");
        Continue1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Continue1ActionPerformed(evt);
            }
        });

        chatBtn.setText("Chat With Newbie");
        chatBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chatBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gradStudentFirstTimerBtn)
                    .addComponent(Continue1)
                    .addComponent(chatBtn))
                .addContainerGap(427, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addComponent(jLabel1)
                .addContainerGap(261, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(86, 86, 86)
                .addComponent(gradStudentFirstTimerBtn)
                .addGap(47, 47, 47)
                .addComponent(Continue1)
                .addGap(55, 55, 55)
                .addComponent(chatBtn)
                .addContainerGap(374, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       

    }//GEN-LAST:event_jButton1ActionPerformed

    private void ContinueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContinueActionPerformed
        
    }//GEN-LAST:event_ContinueActionPerformed

    private void gradStudentFirstTimerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gradStudentFirstTimerBtnActionPerformed
        // TODO add your handling code here:
        GradStudentFirstTimerJPanel gsftJPanel = new GradStudentFirstTimerJPanel(userProcessContainer, enterprise, oorganization);
        userProcessContainer.add("GradStudentFirstTimerJPanel", gsftJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

    }//GEN-LAST:event_gradStudentFirstTimerBtnActionPerformed

    private void Continue1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Continue1ActionPerformed
        // TODO add your handling code here:
        GradStudentRequestJPanel reqJPanel = new GradStudentRequestJPanel(userProcessContainer, account, oorganization, enterprise);
        userProcessContainer.add("GradStudentRequestJPanel", reqJPanel);
        CardLayout layout= (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_Continue1ActionPerformed

    
    private void chatBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chatBtnActionPerformed
        // TODO add your handling code here:
        //System.out.println("2" + evt.hashCode());
        clientJPanel jj = new clientJPanel(userProcessContainer, account, organization, enterprise);
        userProcessContainer.add("clientJPanel", jj);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_chatBtnActionPerformed

    public static void main(String [] args){
        
        System.out.println("main");
        
        test cc = new test();
        //cc.main(args);
        cc.setVisible(true);
        System.out.println("print");
        System.out.println(cc.msg_send.hashCode());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Continue;
    private javax.swing.JButton Continue1;
    private javax.swing.JButton chatBtn;
    private javax.swing.JButton gradStudentFirstTimerBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
