/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.AmbassadorRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.GradStudent.GradStudentDirectory;
import Business.Newbie.NewbieDetailsDirectory;
import Business.Organization.AmbassadorOrganization;
import Business.Organization.DeanOrganization;
import Business.Organization.NewbieOrganization;
import Business.Organization.GradStudentOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.LabTestWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author gaura
 */
public class AmbassadorWorkAreaJPanel extends javax.swing.JPanel {
    
    private JPanel userProcessContainer;
    private EcoSystem business;
    private UserAccount userAccount;
    private AmbassadorOrganization labOrganization;
    private Organization org;
    //private GradStudentDirectory gs;
    //private NewbieDetailsDirectory ns;
    private Enterprise enterprise;
    private GradStudentOrganization gradStudentOrganization;

    /**
     * Creates new form AmbassadorWorkAreaJPanel
     */
    public AmbassadorWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, EcoSystem business, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.business = business;
        //this.organization = (AmbassadorOrganization)organization;
        //this.organization=organization;
        this.org=organization;
        this.enterprise=enterprise;
       // this.gs=gs;
        //this.ns=ns;
        
       
        
    }
    public void populateDeanResponseTbl(){
        
        DefaultTableModel model = (DefaultTableModel) deanResponseTbl.getModel();
        model.setRowCount(0);
        for(WorkRequest request : org.getWorkQueue().getWorkRequestList()){
            Object[] row = new Object[4];
            row[0] = request;
            row[1]=((LabTestWorkRequest) request).getTestResult();
            row[2]=request.getReceiver();
             model.addRow(row);
    }
           }
        
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Studentlist = new javax.swing.JButton();
        handlequeries = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        deanResponseTbl = new javax.swing.JTable();
        deanLoadBtn = new javax.swing.JButton();
        SendBtn = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Studentlist.setText("List of Students");
        Studentlist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentlistActionPerformed(evt);
            }
        });
        add(Studentlist, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 210, -1));

        handlequeries.setText("Handle Newbie Queries");
        handlequeries.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                handlequeriesActionPerformed(evt);
            }
        });
        add(handlequeries, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 200, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Ambassador WorkArea JPanel");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, 320, -1));

        deanResponseTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Message", "Response", "Sender"
            }
        ));
        jScrollPane2.setViewportView(deanResponseTbl);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, -1, 170));

        deanLoadBtn.setText("Load Response from Dean");
        deanLoadBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deanLoadBtnActionPerformed(evt);
            }
        });
        add(deanLoadBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 360, -1, -1));

        SendBtn.setText("Send Mails  to Students");
        SendBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SendBtnActionPerformed(evt);
            }
        });
        add(SendBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 190, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void handlequeriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_handlequeriesActionPerformed
        // TODO add your handling code here:
        
        AmbassadorReqWorkAreaJPanel req = new AmbassadorReqWorkAreaJPanel(userProcessContainer, userAccount, org, business, enterprise);
        userProcessContainer.add("NewbieReqJPanel", req);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_handlequeriesActionPerformed

    private void StudentlistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentlistActionPerformed
        // TODO add your handling code here:
        CollegeAmbassadorWorkAreaJPanel req1 = new CollegeAmbassadorWorkAreaJPanel(enterprise, org);
        userProcessContainer.add("NewbieReqJPanel", req1);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
        
    }//GEN-LAST:event_StudentlistActionPerformed

    private void deanLoadBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deanLoadBtnActionPerformed
        // TODO add your handling code here:
        populateDeanResponseTbl();
        
        
    }//GEN-LAST:event_deanLoadBtnActionPerformed

    private void SendBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SendBtnActionPerformed
        SendMailsToStudentsJPanel req = new SendMailsToStudentsJPanel(enterprise, org);
        userProcessContainer.add("SendmailJPanel", req);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_SendBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SendBtn;
    private javax.swing.JButton Studentlist;
    private javax.swing.JButton deanLoadBtn;
    private javax.swing.JTable deanResponseTbl;
    private javax.swing.JButton handlequeries;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
