/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SuperDean;


import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.ManagerEnterprise;
import Business.Network.Network;
import java.awt.CardLayout;
import javax.swing.JPanel;
import Business.Newbie.NewbieDetailsDirectory;
import Business.Organization.AmbassadorOrganization;
import Business.Organization.NewbieOrganization;
import Business.Organization.DeanOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.Organization.UniversityDeanOrganization;
import Business.WorkQueue.LabTestWorkRequest;
import Business.WorkQueue.WorkRequest;
import javax.swing.table.DefaultTableModel;
//import Business.Organization.UniversityDeanOrganization;
/**
 *
 * @author chels
 */
public class SuperDeanWorkAreaJPanel extends javax.swing.JPanel {
   
        private JPanel userProcessContainer;
        private UserAccount account;
        private  UniversityDeanOrganization udorganization;
        private Enterprise enterprise;
        private Network network;
        private EcoSystem business;
        private Organization org;
       
    

    public SuperDeanWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise, Network network) {
         initComponents();
         this.userProcessContainer=userProcessContainer;
         this.account=account;
         this.udorganization=(UniversityDeanOrganization)organization;
         this.enterprise=enterprise;
         this.business=business;
         this.org=organization;
         this.network=network;
         populate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        assignJButton = new javax.swing.JButton();
        processJButton = new javax.swing.JButton();
        sendAmbassadorBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        udTbl = new javax.swing.JTable();
        assignJButton1 = new javax.swing.JButton();
        processJButton1 = new javax.swing.JButton();
        sendCDeanBtn = new javax.swing.JButton();

        assignJButton.setText("Assign to me");
        assignJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignJButtonActionPerformed(evt);
            }
        });

        processJButton.setText("Process");
        processJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processJButtonActionPerformed(evt);
            }
        });

        sendAmbassadorBtn.setText("Send to Ambassador");
        sendAmbassadorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendAmbassadorBtnActionPerformed(evt);
            }
        });

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("University Dean Work Area");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 11, -1, -1));

        udTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Message", "Sender", "Status", "Response"
            }
        ));
        jScrollPane1.setViewportView(udTbl);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 51, -1, 175));

        assignJButton1.setText("Assign to me");
        assignJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignJButton1ActionPerformed(evt);
            }
        });
        add(assignJButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 278, -1, -1));

        processJButton1.setText("Process");
        processJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processJButton1ActionPerformed(evt);
            }
        });
        add(processJButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(391, 278, -1, -1));

        sendCDeanBtn.setText("Send to College Dean");
        sendCDeanBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendCDeanBtnActionPerformed(evt);
            }
        });
        add(sendCDeanBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 378, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void assignJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignJButtonActionPerformed

       
    }//GEN-LAST:event_assignJButtonActionPerformed

    private void processJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processJButtonActionPerformed
       
    }//GEN-LAST:event_processJButtonActionPerformed

    private void sendAmbassadorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendAmbassadorBtnActionPerformed
       
    }//GEN-LAST:event_sendAmbassadorBtnActionPerformed
     public void populate(){
         
         for(Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()){
             if(enterprise instanceof ManagerEnterprise){
                  DefaultTableModel model = (DefaultTableModel)udTbl.getModel();
        
        model.setRowCount(0);
        
        for(WorkRequest request : enterprise.getWorkQueue().getWorkRequestList()){
            if(request instanceof WorkRequest){
            Object[] row = new Object[4];
            row[0] = request;
            row[1] = request.getSender().getEmployee().getName();
            row[2] = request.getReceiver() == null ? null : request.getReceiver().getEmployee().getName();
            row[3] = request.getStatus();
            
            model.addRow(row);
                 
             }
         }
        
        
             }
         }
     }
    
     
    private void assignJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignJButton1ActionPerformed

        int selectedRow = udTbl.getSelectedRow();

        if (selectedRow < 0){
            return;
        }

        WorkRequest request = (WorkRequest)udTbl.getValueAt(selectedRow, 0);
        request.setReceiver(account);
        request.setStatus("Pending");
        populate();
    }//GEN-LAST:event_assignJButton1ActionPerformed

    private void processJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processJButton1ActionPerformed
        int selectedRow = udTbl.getSelectedRow();

        if (selectedRow < 0){
            return;
        }

        LabTestWorkRequest request = (LabTestWorkRequest)udTbl.getValueAt(selectedRow, 0);

        request.setStatus("Processing");

        SuperDeanProcessWorkRequestJPanel processWorkRequestJPanel = new SuperDeanProcessWorkRequestJPanel(userProcessContainer, request);
        userProcessContainer.add("ProcessWorkRequestSDJPanel", processWorkRequestJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

    }//GEN-LAST:event_processJButton1ActionPerformed

    private void sendCDeanBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendCDeanBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = udTbl.getSelectedRow();
        if (selectedRow < 0){
            return;
        }
        LabTestWorkRequest request = (LabTestWorkRequest)udTbl.getValueAt(selectedRow, 0);
        ((LabTestWorkRequest) request).getTestResult();
        request.getReceiver();
        System.out.println(request.getSender());

    }//GEN-LAST:event_sendCDeanBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton assignJButton;
    private javax.swing.JButton assignJButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton processJButton;
    private javax.swing.JButton processJButton1;
    private javax.swing.JButton sendAmbassadorBtn;
    private javax.swing.JButton sendCDeanBtn;
    private javax.swing.JTable udTbl;
    // End of variables declaration//GEN-END:variables
}
