/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.AdvisorRole;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Newbie.NewbieDetailsDirectory;
import Business.Organization.AmbassadorOrganization;
import Business.Organization.NewbieOrganization;
import Business.Organization.AdvisorOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;
//import userinterface.AmbassadorRole.LabAssistantWorkAreaJPanel;
import Business.Enterprise.Enterprise;
import userinterface.AmbassadorRole.CollegeAmbassadorWorkAreaJPanel;

/**
 *
 * @author Hi
 */
public class AdvisorRoleWorkAreajPanel extends javax.swing.JPanel {
     private JPanel userProcessContainer;
    private EcoSystem business;
    private UserAccount userAccount;
    private AdvisorOrganization labOrganization;
    private Organization organization;
    private Enterprise enterprise;

    /**
     * Creates new form AdvisorRoleWorkAreajPanel
     */
    public AdvisorRoleWorkAreajPanel(JPanel userProcessContainer, UserAccount account, Organization organization, EcoSystem business, Enterprise enterprise) {
        
        initComponents();
         this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.business = business;
        this.labOrganization = (AdvisorOrganization)organization;
        this.organization=organization;
        this.enterprise=enterprise;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Studentlist = new javax.swing.JButton();
        handlequeries = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Studentlist.setText("List of Students");
        Studentlist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentlistActionPerformed(evt);
            }
        });
        add(Studentlist, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, 210, -1));

        handlequeries.setText("Handle Grad Student Queries");
        handlequeries.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                handlequeriesActionPerformed(evt);
            }
        });
        add(handlequeries, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 280, 210, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Advisor WorkArea JPanel");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, 320, -1));

        jButton1.setText("Send mails to All Stuents");
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 360, 210, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void StudentlistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentlistActionPerformed
        // TODO add your handling code here:
        
          ListOfStudentsJPanel req1 = new ListOfStudentsJPanel(enterprise, organization);
        userProcessContainer.add("Studentlist", req1);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
      
        
        
    }//GEN-LAST:event_StudentlistActionPerformed

    private void handlequeriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_handlequeriesActionPerformed
        // TODO add your handling code here:
         WorkRequestJPanel req = new WorkRequestJPanel(userProcessContainer, userAccount, organization, business, enterprise);
        userProcessContainer.add("WorkReqJPanel", req);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

        
    }//GEN-LAST:event_handlequeriesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Studentlist;
    private javax.swing.JButton handlequeries;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
