/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Newbie;

import Business.Employee.Employee;
import Business.Newbie.Newbie;
import Business.Enterprise.Enterprise;
import javax.swing.JPanel;
import Business.Newbie.NewbieDetailsDirectory;
import Business.Organization.Organization;
//mport static Business.Organization.Organization.Type.Newbie;
//import userinterface.AmbassadorRole.LabAssistantWorkAreaJPanel;

import java.awt.CardLayout;
import java.awt.Component;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author gaura
 */
public class NewbieFirstTimerJPanel extends javax.swing.JPanel {

    private JPanel userprocesscontainer;
    private NewbieDetailsDirectory newbieDetailsDirectory;
    private Enterprise enterprise;
    private Organization org;
    /**
     * Creates new form NewbieFirstTimerJPanel
     */
    public NewbieFirstTimerJPanel(JPanel userprocesscontainer,Enterprise enterprise, Organization oorganization) {
        initComponents();
        this.userprocesscontainer = userprocesscontainer;
        this.org=oorganization;
        //this.newbieDetailsDirectory = enterprise.getNds;
        this.enterprise=enterprise;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        newbieSignUpBtn = new javax.swing.JButton();
        TFFname = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        BackBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TFLname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TFmailid = new javax.swing.JTextField();
        courseCB = new javax.swing.JComboBox<>();
        CBfeeling = new javax.swing.JComboBox<>();
        CBethini = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();

        setLayout(null);

        jLabel1.setText("Let us know who you are !");
        add(jLabel1);
        jLabel1.setBounds(300, 30, 190, 14);

        jLabel8.setText("Course:");
        add(jLabel8);
        jLabel8.setBounds(140, 180, 38, 14);

        jLabel9.setText("FirstName:");
        add(jLabel9);
        jLabel9.setBounds(139, 114, 52, 14);

        newbieSignUpBtn.setText("Submit");
        newbieSignUpBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newbieSignUpBtnActionPerformed(evt);
            }
        });
        add(newbieSignUpBtn);
        newbieSignUpBtn.setBounds(180, 340, 67, 23);
        add(TFFname);
        TFFname.setBounds(230, 110, 72, 20);
        add(jLabel10);
        jLabel10.setBounds(139, 195, 0, 0);

        BackBtn.setText("Back");
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });
        add(BackBtn);
        BackBtn.setBounds(50, 480, 100, 23);

        jLabel2.setText("Feeling:");
        add(jLabel2);
        jLabel2.setBounds(140, 220, 38, 14);

        jLabel3.setText("LastName:");
        add(jLabel3);
        jLabel3.setBounds(140, 150, 51, 14);
        add(TFLname);
        TFLname.setBounds(230, 150, 70, 20);

        jLabel4.setText("Ethinicity:");
        add(jLabel4);
        jLabel4.setBounds(140, 260, 47, 14);

        jLabel5.setText("Email-ID");
        add(jLabel5);
        jLabel5.setBounds(140, 290, 39, 14);

        TFmailid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFmailidActionPerformed(evt);
            }
        });
        add(TFmailid);
        TFmailid.setBounds(230, 290, 80, 20);

        courseCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MSIS", "MSEM", "MSTSM" }));
        add(courseCB);
        courseCB.setBounds(230, 180, 80, 22);

        CBfeeling.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Happy", "Nervous", "Confused", "Depressed" }));
        add(CBfeeling);
        CBfeeling.setBounds(230, 220, 80, 22);

        CBethini.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Indian", "Chinese", "American" }));
        add(CBethini);
        CBethini.setBounds(230, 260, 80, 22);

        jPanel1.setLayout(null);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/Newbie/who are you.jpg"))); // NOI18N
        jPanel1.add(jLabel6);
        jLabel6.setBounds(0, 20, 210, 310);

        add(jPanel1);
        jPanel1.setBounds(500, 50, 330, 440);
    }// </editor-fold>//GEN-END:initComponents

    private void newbieSignUpBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newbieSignUpBtnActionPerformed
        // TODO add your handling code here:
        //NewbieDetailsDirectory nds = enterprise.getNds();
        String name = TFFname.getText();
        //String course = TFcourse.getText();
        String ethini = (String)CBethini.getSelectedItem();
        String Email = TFmailid.getText();
        String lastn = TFLname.getText();
        String feeling = (String)CBfeeling.getSelectedItem();
        String cour = (String)courseCB.getSelectedItem();
        
       
        
        if(TFFname.getText().isEmpty() || TFLname.getText().isEmpty() || TFmailid.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null,"Please fill all the fields");
            
            
        }
        
        else if(!name.matches("[a-z,A-Z,]+") && !lastn.matches("[a-z,A-Z,]+"))
        {
           JOptionPane.showMessageDialog(null,"Please enter characters for names fields"); 
        }
        
       
       else
        {
            
        if(!(Pattern.matches("^[a-zA-Z0-9]+[@]{1}[a-zA-Z0-9]+[.]{1}+[a-zA-Z0-9]+$", TFmailid.getText()))){
            JOptionPane.showMessageDialog(null,"Please enter a valid e-mail");
        }
        else {
             Newbie n = org.getNds().createNewbie();
        n.setFirstName(name);
        n.setEmailID(Email);
        n.setEthinicity(ethini);
        n.setFeeling(feeling);
        n.setLastName(lastn);
        n.setMajorAccepted(cour);
        newbieSignUpBtn.setEnabled(false);
        JOptionPane.showMessageDialog(null,"Successfully Submitted");
        }
        }
    

    }//GEN-LAST:event_newbieSignUpBtnActionPerformed

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
        // TODO add your handling code here:

        userprocesscontainer.remove(this);
        Component[] componentArray = userprocesscontainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        NewbieWorkAreaJPanel dwjp = (NewbieWorkAreaJPanel) component;
        //dwjp.populateTable();
        CardLayout layout = (CardLayout) userprocesscontainer.getLayout();
        layout.previous(userprocesscontainer);
    }//GEN-LAST:event_BackBtnActionPerformed

    private void TFmailidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFmailidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFmailidActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackBtn;
    private javax.swing.JComboBox<String> CBethini;
    private javax.swing.JComboBox<String> CBfeeling;
    private javax.swing.JTextField TFFname;
    private javax.swing.JTextField TFLname;
    private javax.swing.JTextField TFmailid;
    private javax.swing.JComboBox<String> courseCB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton newbieSignUpBtn;
    // End of variables declaration//GEN-END:variables
}
