/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Newbie;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import java.awt.CardLayout;
import javax.swing.JPanel;
import Business.Newbie.NewbieDetailsDirectory;
import Business.Organization.AmbassadorOrganization;
import Business.Organization.NewbieOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;

/**
 *
 * @author gaura
 */
public class NewbieWorkAreaJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private NewbieDetailsDirectory newbieDetailsDirectory;

    private EcoSystem business;
    private UserAccount account;
    private NewbieOrganization oorganization;
    private Organization organization;
    private Enterprise enterprise;

    /**
     * Creates new form NewbieWorkAreaJPanel
     */
    public NewbieWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, NewbieOrganization organization, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.newbieDetailsDirectory=newbieDetailsDirectory;
        this.account=account;
        this.oorganization=organization;
        this.enterprise=enterprise;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Continue = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Newbie Work Area");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, -1, -1));

        jButton1.setText("FirstTimer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, -1, -1));

        Continue.setText("Continue");
        Continue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContinueActionPerformed(evt);
            }
        });
        add(Continue, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        NewbieFirstTimerJPanel newbiefirstJPanel = new NewbieFirstTimerJPanel(userProcessContainer, enterprise, oorganization);
        userProcessContainer.add("NewbieFirstTimerJPanel", newbiefirstJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ContinueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContinueActionPerformed
        // TODO add your handling code here:
        userinterface.Newbie.NewbieRequestJPanel newbiereqJPanel = new userinterface.Newbie.NewbieRequestJPanel(userProcessContainer, account, oorganization, enterprise);
        userProcessContainer.add("NewbieReqJPanel", newbiereqJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_ContinueActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Continue;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
